//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticSphere.Specifics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticSphere.Specifics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property is required..
        /// </summary>
        internal static string FluentIsRequiredDefaultMessage {
            get {
                return ResourceManager.GetString("FluentIsRequiredDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_IsRequired.
        /// </summary>
        internal static string FluentIsRequiredName {
            get {
                return ResourceManager.GetString("FluentIsRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property must match the pattern &apos;{1}&apos;..
        /// </summary>
        internal static string FluentMatchesPatternDefaultMessage {
            get {
                return ResourceManager.GetString("FluentMatchesPatternDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_MatchesPattern.
        /// </summary>
        internal static string FluentMatchesPatternName {
            get {
                return ResourceManager.GetString("FluentMatchesPatternName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property must be no more than {1} characters long..
        /// </summary>
        internal static string FluentMaximumLengthDefaultMessage {
            get {
                return ResourceManager.GetString("FluentMaximumLengthDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_MaximumLength.
        /// </summary>
        internal static string FluentMaximumLengthName {
            get {
                return ResourceManager.GetString("FluentMaximumLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property must be at least {1} characters long..
        /// </summary>
        internal static string FluentMinimumLengthDefaultMessage {
            get {
                return ResourceManager.GetString("FluentMinimumLengthDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_MinimumLength.
        /// </summary>
        internal static string FluentMinimumLengthName {
            get {
                return ResourceManager.GetString("FluentMinimumLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided to the &quot;property&quot; parameter is not a property..
        /// </summary>
        internal static string InvalidPropertyError {
            get {
                return ResourceManager.GetString("InvalidPropertyError", resourceCulture);
            }
        }
    }
}
